//imports
import Gallery from "components/Gallery";
import Hero from "components/Hero";
import Navbar from "components/NavBar";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Brookyln NightClub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar className=" sticky" />
      <Hero heading="JOIN THE CLUB" message="WELCOME TO THE PARTY" />
      <Gallery />
    </div>
  );
}
