import { auth, db } from "../../firebaseConfig";
import { signInWithPopup, GoogleAuthProvider } from "firebase/auth";
import { useAuthState } from "react-firebase-hooks/auth";
import { useEffect } from "react";
import { distDir } from "next.config";
import Link from "next/link";
import Head from "next/head";
import Router from "next/router";
import { doc, getDoc } from "firebase/firestore";

export default function Members() {
  const [user, setUser] = useAuthState(auth);
  const googleAuth = new GoogleAuthProvider();
  const login = async () => {
    const result = await signInWithPopup(auth, googleAuth);
  };

  const phoneRetireve = async () => {
    if (user) {
      const docRef = doc(db, "users", user.email);
      const docSnap = await getDoc(docRef);
      if (!docSnap.data().phoneNumber) {
        Router.replace("/Profile");
      } else {
        console.log("Phone number exists: " + docSnap.data().phoneNumber);
      }
    }
  };

  useEffect(() => {
    phoneRetireve();
  }, [user]);
  if (user && !user) {
  }

  return (
    <>
      <Head>
        <title>Members</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Link href="/Profile">Users</Link>
        <div>Members</div>
        {!user && <button onClick={login}>Login</button>}
        {user ? "Welcome " + user.displayName : ""}
        <div>
          {user && <button onClick={() => auth.signOut()}>Signout</button>}
        </div>
      </main>
    </>
  );
}
