import Head from "next/head";
import { auth, db } from "../../firebaseConfig";
import { useAuthState } from "react-firebase-hooks/auth";
import { useForm } from "react-hook-form";
import { getAuth, updateProfile } from "firebase/auth";
import { doc, setDoc, getDoc } from "firebase/firestore";
import { useState, useEffect } from "react";
import Router from "next/router";

export default function Profile() {
  //required for name change
  const auth = getAuth();
  const [user, setUser] = useAuthState(auth);
  const { register, handleSubmit } = useForm();
  const [phone, setPhone] = useState("");
  const [name, setName] = useState("");

  //For Sending To database
  const updateDatabase = (data) => {
    setName(data.name);

    //Update name on auth side
    updateProfile(auth.currentUser, {
      displayName: data.name,
    })
      .then(() => {
        console.log("User name Updated!");
      })
      .catch((error) => {
        // An error occurred
        // ...
      });
    console.log(data.name);

    //Update Name and Phone on database side
    setDoc(doc(db, "users", user.email), {
      name: data.name,
      emailID: user && user.email ? user.email : "NoEmail",
      phoneNumber: "+91" + data.phone,
    });

    console.log("Added to database!");
  };

  //Retrieves from database
  const readDatabase = async () => {
    if (user) {
      const docRef = doc(db, "users", user.email);
      const docSnap = await getDoc(docRef);
      if (!docSnap.data().phoneNumber) {
        Router.replace("/Profile");
      } else {
        console.log("Phone number exists: " + docSnap.data().phoneNumber);
        setName(docSnap.data().name);
        setPhone(docSnap.data().phoneNumber.slice(3));
      }
    }
  };
  useEffect(() => {
    readDatabase();
    if (!user) {
      Router.replace("/members");
    }
  }, [user]);

  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <div>Name: {user ? name : ""}</div>
          <div>Email: {user ? user.email : ""}</div>
        </div>

        <form onSubmit={handleSubmit(updateDatabase)}>
          <label htmlFor="name">Name</label>
          <input
            type="name"
            defaultValue={user ? name : ""}
            {...register("name", { required: true })}
          />
          <div className="m-10"></div>
          <label htmlFor="phone">Phone Number</label>
          <input
            type="phone"
            defaultValue={user && phone ? phone : ""}
            {...register("phone", {
              required: true,
              minLength: 10,
              maxLength: 10,
            })}
          />

          <button>Update DB</button>
        </form>
        <div>
          {user && <button onClick={() => auth.signOut()}>Signout</button>}
        </div>
      </main>
    </>
  );
}
